### ISSUE TITLE
Release alpha to NuGet

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/FeatherHttp#13]
The APIs are almost in a good enough state to get to an alpha. I don't think we need to docs site for that but we should iterate on it to get the APIs more stable. Pushing to nuget should help with getting a broader set of feedback from bleeding edge customers.

**Comment by davidfowl** [comment]
Now I need to figure out how to have cleaner versions than git version provides for an alpha!

**Comment by RobotOptimist** [comment]
It's not so bad, you can't use actions/checkout@v1, or at least I haven't been able to get it to work with that, so first things first
in your version.json:

```
"publicReleaseRefSpec": [
        "^refs/heads/master$"
    ]
```
this designates that your master branch is the release branch and should not have the `-g00fevc` stuff appended to the version - although it might be cool to have a designated release branch other than master, i dunno though

next you'll update to actions/checkout@v2 and it will look like this:

```
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - run: |
         git fetch --prune --unshallow origin HEAD
```
if you try to checkout the committing branch using checkout@v1 then git versioning will throw a bunch of errors, using v2 and fetching seems to consistently work

let me know if you'd prefer this via a PR though
